# -*- coding: utf-8  -*-

from wikidata import Wikidata

Wikidata(pages=[
    { 'rules': { 300: u'RU-AMU' }, 'name': u'Амурская область' },
    { 'rules': { 300: u'RU-ARK' }, 'name': u'Архангельская область' },
    { 'rules': { 300: u'RU-AST' }, 'name': u'Астраханская область' },
    { 'rules': { 300: u'RU-BEL' }, 'name': u'Белгородская область' },
    { 'rules': { 300: u'RU-BRY' }, 'name': u'Брянская область' },
    { 'rules': { 300: u'RU-VLA' }, 'name': u'Владимирская область' },
    { 'rules': { 300: u'RU-VGG' }, 'name': u'Волгоградская область' },
    { 'rules': { 300: u'RU-VLG' }, 'name': u'Вологодская область' },
    { 'rules': { 300: u'RU-VOR' }, 'name': u'Воронежская область' },
    { 'rules': { 300: u'RU-IVA' }, 'name': u'Ивановская область' },
    { 'rules': { 300: u'RU-IRK' }, 'name': u'Иркутская область' },
    { 'rules': { 300: u'RU-KGD' }, 'name': u'Калининградская область' },
    { 'rules': { 300: u'RU-KLU' }, 'name': u'Калужская область' },
    { 'rules': { 300: u'RU-KEM' }, 'name': u'Кемеровская область' },
    { 'rules': { 300: u'RU-KIR' }, 'name': u'Кировская область' },
    { 'rules': { 300: u'RU-KOS' }, 'name': u'Костромская область' },
    { 'rules': { 300: u'RU-KGN' }, 'name': u'Курганская область' },
    { 'rules': { 300: u'RU-KRS' }, 'name': u'Курская область' },
    { 'rules': { 300: u'RU-LEN' }, 'name': u'Ленинградская область' },
    { 'rules': { 300: u'RU-LIP' }, 'name': u'Липецкая область' },
    { 'rules': { 300: u'RU-MAG' }, 'name': u'Магаданская область' },
    { 'rules': { 300: u'RU-MOS' }, 'name': u'Московская область' },
    { 'rules': { 300: u'RU-MUR' }, 'name': u'Мурманская область' },
    { 'rules': { 300: u'RU-NIZ' }, 'name': u'Нижегородская область' },
    { 'rules': { 300: u'RU-NGR' }, 'name': u'Новгородская область' },
    { 'rules': { 300: u'RU-NVS' }, 'name': u'Новосибирская область' },
    { 'rules': { 300: u'RU-OMS' }, 'name': u'Омская область' },
    { 'rules': { 300: u'RU-ORE' }, 'name': u'Оренбургская область' },
    { 'rules': { 300: u'RU-ORL' }, 'name': u'Орловская область' },
    { 'rules': { 300: u'RU-PNZ' }, 'name': u'Пензенская область' },
    { 'rules': { 300: u'RU-PSK' }, 'name': u'Псковская область' },
    { 'rules': { 300: u'RU-ROS' }, 'name': u'Ростовская область' },
    { 'rules': { 300: u'RU-RYA' }, 'name': u'Рязанская область' },
    { 'rules': { 300: u'RU-SAM' }, 'name': u'Самарская область' },
    { 'rules': { 300: u'RU-SAR' }, 'name': u'Саратовская область' },
    { 'rules': { 300: u'RU-SAK' }, 'name': u'Сахалинская область' },
    { 'rules': { 300: u'RU-SVE' }, 'name': u'Свердловская область' },
    { 'rules': { 300: u'RU-SMO' }, 'name': u'Смоленская область' },
    { 'rules': { 300: u'RU-TAM' }, 'name': u'Тамбовская область' },
    { 'rules': { 300: u'RU-TVE' }, 'name': u'Тверская область' },
    { 'rules': { 300: u'RU-TOM' }, 'name': u'Томская область' },
    { 'rules': { 300: u'RU-TUL' }, 'name': u'Тульская область' },
    { 'rules': { 300: u'RU-TYU' }, 'name': u'Тюменская область' },
    { 'rules': { 300: u'RU-ULY' }, 'name': u'Ульяновская область' },
    { 'rules': { 300: u'RU-CHE' }, 'name': u'Челябинская область' },
    { 'rules': { 300: u'RU-YAR' }, 'name': u'Ярославская область' },
    { 'rules': { 300: u'RU-AD' }, 'name': u'Адыгея' },
    { 'rules': { 300: u'RU-BA' }, 'name': u'Башкортостан' },
    { 'rules': { 300: u'RU-BU' }, 'name': u'Бурятия' },
    { 'rules': { 300: u'RU-DA' }, 'name': u'Дагестан' },
    { 'rules': { 300: u'RU-IN' }, 'name': u'Ингушетия' },
    { 'rules': { 300: u'RU-KB' }, 'name': u'Кабардино-Балкария' },
    { 'rules': { 300: u'RU-KL' }, 'name': u'Калмыкия' },
    { 'rules': { 300: u'RU-KC' }, 'name': u'Карачаево-Черкесия' },
    { 'rules': { 300: u'RU-KR' }, 'name': u'Карелия' },
    { 'rules': { 300: u'RU-ME' }, 'name': u'Марий Эл' },
    { 'rules': { 300: u'RU-MO' }, 'name': u'Мордовия' },
    { 'rules': { 300: u'RU-AL' }, 'name': u'Республика Алтай' },
    { 'rules': { 300: u'RU-KO' }, 'name': u'Республика Коми' },
    { 'rules': { 300: u'RU-SA' }, 'name': u'Республика Саха' },
    { 'rules': { 300: u'RU-SE' }, 'name': u'Северная Осетия' },
    { 'rules': { 300: u'RU-TA' }, 'name': u'Татарстан' },
    { 'rules': { 300: u'RU-TY' }, 'name': u'Тува' },
    { 'rules': { 300: u'RU-UD' }, 'name': u'Удмуртия' },
    { 'rules': { 300: u'RU-KK' }, 'name': u'Хакасия' },
    { 'rules': { 300: u'RU-CE' }, 'name': u'Чеченская республика' },
    { 'rules': { 300: u'RU-CU' }, 'name': u'Чувашия' },
    { 'rules': { 300: u'RU-ALT' }, 'name': u'Алтайский край' },
    { 'rules': { 300: u'RU-ZAB' }, 'name': u'Забайкальский край' },
    { 'rules': { 300: u'RU-KAM' }, 'name': u'Камчатский край' },
    { 'rules': { 300: u'RU-KDA' }, 'name': u'Краснодарский край' },
    { 'rules': { 300: u'RU-KYA' }, 'name': u'Красноярский край' },
    { 'rules': { 300: u'RU-PER' }, 'name': u'Пермский край' },
    { 'rules': { 300: u'RU-PRI' }, 'name': u'Приморский край' },
    { 'rules': { 300: u'RU-STA' }, 'name': u'Ставропольский край' },
    { 'rules': { 300: u'RU-KHA' }, 'name': u'Хабаровский край' },
    { 'rules': { 300: u'RU-NEN' }, 'name': u'Ненецкий автономный округ' },
    { 'rules': { 300: u'RU-KHM' }, 'name': u'Ханты-Мансийский автономный округ' },
    { 'rules': { 300: u'RU-CHU' }, 'name': u'Чукотский автономный округ' },
    { 'rules': { 300: u'RU-YAN' }, 'name': u'Ямало-Ненецкий автономный округ' },
    { 'rules': { 300: u'RU-SPE' }, 'name': u'Санкт-Петербург' },
    { 'rules': { 300: u'RU-MOW' }, 'name': u'Москва' },
    { 'rules': { 300: u'RU-YEV' }, 'name': u'Еврейская автономная область' },
])

